### ISSUE TITLE
About your setting

### ISSUE THREAD

**Issue by Grady10086** [B0B8K1ng/WMNavigation#3]
Nice work，but why does your paper say 0.1 for the distance threshold but you use 1 in your config?

**Comment by B0B8K1ng** [comment]
Thank you for your valuable feedback. Since the currently available version of the paper is an early draft and is still being updated, there may be some oversights. Please refer to the settings in the code as correct and we use 1.0 as the distance threshold, which is consistent with the settings in most other related works. We have corrected this error in the paper. We apologize for the confusion caused by our oversight.

**Comment by Grady10086** [comment]
I also found other questions that I would like to be answered:1, the configuration of your agent is not consistent with VLMnav, what is the reason for this.2, I noticed that the part of your World Model actually serves to go to make a selection of the view angle of the surround view map, so have you done a comparison of the initial configurations, for example, the difference of the navigational effect of the 124/131° view angle ( I'm curious how your SPL achieves 0.3+, if you tell me it will help me a lot, I've been doing research recently, the SR is 0.62 but the SPL is only 0.2+ in 124° single view angle, is it because of the threshold selection (0.3 vs 1.0), if you've done the relevant experiments in the first place, I believe it will help me a lot. I'm sure it would help me a lot

**Comment by Grady10086** [comment]
Thank you very much for your response, but I still have some questions: 1. Stop Threshold: Most of the methods you compared use a stop threshold of 0.2m. Does this create an unfair comparison? 2. Can the look-around component of your method be considered an additional action for the agent, similar to the cost of looking around being equivalent to observing six steps within the HFoV?
